### ISSUE TITLE
type of FuncDef::body: Stmt or Stmt*?

### ISSUE THREAD

**Issue by ekiwi** [cs294-141/assignment1#2]
The `IR` defines `FuncDef` like this:
```.py
FuncDef(Str name, Str* args, Stmt body)
```
Thus the `body` is a single statement.

However, the example `visit_FunctionDef` implementation assigns a list of `Stmt` (which would be `Stmt*`) to the `body` of the new `FuncDef` node:
```.py
body = [self.visit(stmt) for stmt in func.body]
return FuncDef(func.name, [], body)
```

There are two ways to fix this:
1.) change the `IR` definition to `FuncDef(Str name, Str* args, Stmt* body)`
     (and for symmetry reasons `If(Expr cond, Stmt* body, (Stmt*)? elseBody)` etc.)
2.) use the `Block` node in `visit_FunctionDef` if there is more than one statement in the original functions definition

**Comment by jrk** [comment]
Sorry, I wasn’t receiving notifications for some reason.

I updated the starter code around the time you posted this to use a single Return statement and not confusingly stick a Python list into the IR. The original code was a mistake—my intention was for you to use Block nodes to explicitly store lists of statements within a single parent statement. I believe this corresponds to your option (2)
