### ISSUE TITLE
do we need to create our own representation of the operations

### ISSUE THREAD

**Issue by yifanwu** [cs294-141/assignment1#4]
I'm talking about the `Uop`, `Bop`, and `Cop` or can we just use existing ones? http://greentreesnakes.readthedocs.io/en/latest/nodes.html#Add.

/cc @jrk just to be sure you see this.

**Comment by jrk** [comment]
You’re welcome to use whatever you want. I expected most people would just use strings for these, since there generally isn’t a much richer way of representing enums in Python, and this code is simple and small enough that encapsulating and abstracting the string constants doesn’t seem critical.
